const Autocomplete = {
  geocoding: {
    version: "0.2",
    attribution: "http://pelias.mapzen.com/v1/attribution",
    query: {
      layers: ["venue"],
      sources: ["openstreetmap", "whosonfirst"],
      size: 10,
      private: false,
      "point.lat": 59.907875,
      "point.lon": 10.755851,
      "boundary.circle.radius": 0.5,
      "boundary.circle.lat": 59.907875,
      "boundary.circle.lon": 10.755851,
      lang: {
        name: "English",
        iso6391: "en",
        iso6393: "eng",
        defaulted: false,
      },
      querySize: 20,
    },
    engine: {
      name: "Pelias",
      author: "Mapzen",
      version: "1.0",
    },
    timestamp: 1709622738972,
  },
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [10.7569, 59.908077],
      },
      properties: {
        id: "NSR:StopPlace:58367",
        gid: "openstreetmap:venue:NSR:StopPlace:58367",
        layer: "venue",
        source: "openstreetmap",
        source_id: "NSR:StopPlace:58367",
        name: "Bjørvika",
        street: "NOT_AN_ADDRESS-NSR:StopPlace:58367",
        confidence: 0.8,
        distance: 0.063,
        accuracy: "point",
        country_a: "NOR",
        county: "Oslo",
        county_gid: "whosonfirst:county:KVE:TopographicPlace:03",
        locality: "Oslo",
        locality_gid: "whosonfirst:locality:KVE:TopographicPlace:0301",
        label: "Bjørvika, Oslo",
        category: ["onstreetBus", "onstreetTram"],
        tariff_zones: [
          "OST:TariffZone:227",
          "BRA:TariffZone:311",
          "RUT:FareZone:4",
          "RUT:TariffZone:1",
          "INN:TariffZone:2100",
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [10.75356, 59.905706],
      },
      properties: {
        id: "NSR:StopPlace:61482",
        gid: "whosonfirst:venue:NSR:StopPlace:61482",
        layer: "venue",
        source: "whosonfirst",
        source_id: "NSR:StopPlace:61482",
        name: "Munch Bjørvika",
        street: "NOT_AN_ADDRESS-NSR:StopPlace:61482",
        confidence: 0.6,
        distance: 0.274,
        accuracy: "point",
        country_a: "NOR",
        county: "Oslo",
        county_gid: "whosonfirst:county:KVE:TopographicPlace:03",
        locality: "Oslo",
        locality_gid: "whosonfirst:locality:KVE:TopographicPlace:0301",
        label: "Munch Bjørvika, Oslo",
        category: ["ferryStop"],
        tariff_zones: [
          "BRA:TariffZone:311",
          "RUT:FareZone:4",
          "RUT:TariffZone:1",
          "INN:TariffZone:2100",
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [10.753051, 59.910357],
      },
      properties: {
        id: "NSR:StopPlace:59872",
        gid: "openstreetmap:venue:NSR:StopPlace:59872",
        layer: "venue",
        source: "openstreetmap",
        source_id: "NSR:StopPlace:59872",
        name: "Oslo S",
        street: "NOT_AN_ADDRESS-NSR:StopPlace:59872",
        confidence: 0.6,
        distance: 0.318,
        accuracy: "point",
        country_a: "NOR",
        county: "Oslo",
        county_gid: "whosonfirst:county:KVE:TopographicPlace:03",
        locality: "Oslo",
        locality_gid: "whosonfirst:locality:KVE:TopographicPlace:0301",
        label: "Oslo S, Oslo",
        category: ["onstreetBus", "railStation", "onstreetBus"],
        tariff_zones: [
          "OST:TariffZone:227",
          "BRA:TariffZone:311",
          "RUT:FareZone:4",
          "RUT:TariffZone:1",
          "INN:TariffZone:2100",
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [10.759488, 59.911318],
      },
      properties: {
        id: "NSR:StopPlace:58293",
        gid: "openstreetmap:venue:NSR:StopPlace:58293",
        layer: "venue",
        source: "openstreetmap",
        source_id: "NSR:StopPlace:58293",
        name: "Oslo bussterminal",
        street: "NOT_AN_ADDRESS-NSR:StopPlace:58293",
        confidence: 0.6,
        distance: 0.434,
        accuracy: "point",
        country_a: "NOR",
        county: "Oslo",
        county_gid: "whosonfirst:county:KVE:TopographicPlace:03",
        locality: "Oslo",
        locality_gid: "whosonfirst:locality:KVE:TopographicPlace:0301",
        label: "Oslo bussterminal, Oslo",
        category: ["onstreetBus", "onstreetBus", "onstreetBus", "busStation"],
        tariff_zones: [
          "OST:TariffZone:227",
          "BRA:TariffZone:311",
          "RUT:FareZone:4",
          "RUT:TariffZone:1",
          "INN:TariffZone:2100",
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [10.758968, 59.903816],
      },
      properties: {
        id: "NSR:StopPlace:6529",
        gid: "whosonfirst:venue:NSR:StopPlace:6529",
        layer: "venue",
        source: "whosonfirst",
        source_id: "NSR:StopPlace:6529",
        name: "Sørenga",
        street: "NOT_AN_ADDRESS-NSR:StopPlace:6529",
        confidence: 0.6,
        distance: 0.485,
        accuracy: "point",
        country_a: "NOR",
        county: "Oslo",
        county_gid: "whosonfirst:county:KVE:TopographicPlace:03",
        locality: "Oslo",
        locality_gid: "whosonfirst:locality:KVE:TopographicPlace:0301",
        label: "Sørenga, Oslo",
        category: ["onstreetBus"],
        tariff_zones: [
          "OST:TariffZone:227",
          "RUT:FareZone:4",
          "RUT:TariffZone:1",
          "INN:TariffZone:2100",
        ],
      },
    },
  ],
  bbox: [10.753051, 59.903816, 10.759488, 59.911318],
};

export default Autocomplete;
